# -*- coding: utf-8 -*-
"""Scp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-lmECGeCXH1SWJ6etY0-OrYQKGw-LND
"""

n1= int(input('Enter the first number:'))
n2 = int(input('Enter the second number:'))
if n1>n2:
  print('The number',n1,'is greater than',n2) 
else:
  print('The number',n2,'is greater than',n1)

n1= int(input('Enter the first number:'))
n2 = int(input('Enter the second number:'))
if n1<n2:
  print('The number',n1,'is smaller than',n2) 
else:
  print('The number',n2,'is smaller than',n1)