# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/185INc1dwOA94fBVwEczelyOzh7e0ITLH
"""

a=int(input ('enter a number1='))
b=int(input ('enter a number1='))

if a>b:
    print('The larger number is={}'.format(a))
else:
    print('The larger number is={}'.format(b))