# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14z5BYYsUW9xCFVCOvuXI3xOn_8lW2oOE
"""

a=int(input ('enter a number1='))
b=int(input ('enter a number2='))

if a<b:
    print('The smaller number is={}'.format(a))
else:
    print('The smaller number is={}'.format(b))