# -*- coding: utf-8 -*-
"""Script_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dC9td5l5EFeIBga_HDfoFA7WoxhirXiq
"""

a=int(input ('enter a number1 = '))
b=int(input ('enter a number2 = '))

if a<b:
    print('The smaller number is = {}'.format(a))
else:
    print('The smaller number is = {}'.format(b))