# -*- coding: utf-8 -*-
"""Script_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14_r124ckXdwqhZOyxdo86sIdOFj0inN2
"""

a=int(input ('enter a number1 = '))
b=int(input ('enter a number1 = '))

if a>b:
    print('The larger number is = {}'.format(a))
else:
    print('The larger number is = {}'.format(b))